### PR TITLE
Add a isConnected public method for the client

### PR DESCRIPTION
**Pull request by cristhianfernandez01**
Hi, my idea is to use the $connected attribute for determinate the status (connected or not) for the websocket client. For this reason, I want to add a method for thus I can check the value of this attribute. Greetings

### CODE REVIEW

**Comment by jjsaunier** [comment]
Thank you @cristhianfernandez01

**Comment by cristhianfernandez01** [comment]
You're welcome! I have another request. Could you update dependencies composer of WebsocketBundle so that WebsocketPhpClient use version 0.1.2 instead of version 0.1.0?

**Comment by cristhianfernandez01** [comment]
My mistake, the composer.json WebsocketBundle file is correct and that always considers the latest version of WebsocketPhpClient. Excuse my silly request. Regards.

**Comment by jjsaunier** [comment]
no problem

**Pull request merged**
